Algoritmo "ExerciciosWord77"
// Disciplina   : [Lógica de Programação]
// Professor   : Jiason
// Descrição   : Crie um programa que exiba os números ímpares de 50 a 1
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2023
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 50 passo 2 faca
      Escreval(contadora)
   fimpara

Fimalgoritmo