Algoritmo "ExerciciosWord51"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Faça um programa que exiba os números de 1 a 10 usando
// o loop "do-while".
// Autor(a)    : Hernando
// Data atual  : 18/09/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 1
   repita
      Escreval(numero)
      numero <- numero + 1
   ate numero > 10

Fimalgoritmo