Algoritmo "ExerciciosWord66"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Faça um programa que exiba os números de 1 a 10.
// Autor(a)    : Hernando
// Data atual  : 21/09/2023
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 10 passo 1 faca
      Escreval(contadora)
   fimpara

Fimalgoritmo