Algoritmo "ExerciciosWord68"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Crie um programa que exiba os números pares de 1 a 50.
// Autor(a)    : Hernando
// Data atual  : 21/09/2023
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 0 ate 50 passo 2 faca
      Escreval(contadora)
   fimpara

Fimalgoritmo